# TO USE THIS CORRECTLY, INSTALL VSCODE EXTENSION "REST CLIENT"

### VARIABLES ==================================================================

@hostname = http://localhost:3000

### ROUTES =====================================================================

GET {{hostname}}

### ============================================================================

GET {{hostname}}/error

### ============================================================================

GET {{hostname}}/exit
