name: callable - node.js CI

on: [workflow_call]

jobs:
  nodejs-ci:
    runs-on: ubuntu-latest
    steps:
    - name: 1 - checkout the repository
      uses: actions/checkout@v3

    - name: 2 - Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: 3 - install dependencies
      run: echo npm install

    - name: 4 - build package
      run: echo npm run build --if-present

    - name: 5 - run tests
      run: echo npm run test --if-present
