#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🐶 husky script: [pre-push]"
npm run update
git add boilerplates/boilerplates.json
git add README.MD
git commit --amend --no-edit
echo "✅ husky script: [pre-push]"
echo ""

