#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🐶 husky script: [pre-commit]"
npm run update
git add boilerplates/boilerplates.json
git add README.MD
git add .
echo "✅ husky script: [pre-commit]"
echo ""

